"""create destinations table

Revision ID: c4eccab51eac
Revises: 8de11ced27ed
Create Date: 2026-09-02 09:48:04.756145

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4eccab51eac"
down_revision: str | Sequence[str] | None = "8de11ced27ed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "destinations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("climate", sa.String(length=100), nullable=True),
        sa.Column("attractions", sa.JSON(), nullable=True),
        sa.Column("best_seasons", sa.JSON(), nullable=True),
        sa.Column("avg_cost_per_day", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_destinations")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("destinations")
    # ### end Alembic commands ###
